services:
  # STACK
  mongo:
    image: mongo:8.0.3-noble
    ports:
      - "27017:27017"
    restart: "no"
    volumes:
      - mongo_data:/data/db
    networks:
      - zumely
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      retries: 10
      timeout: 10s
      interval: 10s
  rabbitmq:
    image: rabbitmq:4.1.4-management
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
      - "15674:15674" # STOMP WebSocket
      - "61613:61613" # STOMP
    restart: "no"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - zumely
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST:-/}
    command: >
      bash -c "
        rabbitmq-plugins enable --offline rabbitmq_management rabbitmq_stomp rabbitmq_web_stomp &&
        rabbitmq-server
      "
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      retries: 10
      timeout: 10s
      interval: 10s
volumes:
  mongo_data:
  rabbitmq_data:
  rabbitmq_log:

networks:
  zumely:
    driver: bridge
